src/Entity/NodeCommand.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\NodeCommandRepository")
 * @ORM\Table(name="commands", uniqueConstraints={@ORM\UniqueConstraint(name="unique_key_plant", columns={"cmd_key", "plant_id"})})
 * @ORM\HasLifecycleCallbacks()
 */
class NodeCommand
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="bigint", options={"unsigned"=true})
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $cmd_key = '';

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $cmd_value = '';

    /**
     * @ORM\Column(type="boolean", options={"default"="0"})
     */
    private $published = false;

    /**
     * @ORM\Column(type="boolean", options={"default"="0"})
     */
    private $received = false;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updatedAt;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Plant", inversedBy="nodeCommands")
     * @ORM\JoinColumn(name="plant_id", nullable=false)
     */
    private $plant;

    /**
     * @ORM\Column(type="boolean", options={"default"="0"})
     */
    private $can_be_deleted = false;


    public function __construct()
    {
        $this->setCreatedAt(new \DateTime());
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCmdKey(): string
    {
        return $this->cmd_key;
    }

    public function setCmdKey(string $cmd_key): self
    {
        $this->cmd_key = $cmd_key;

        return $this;
    }

    public function getCmdValue(): string
    {
        return $this->cmd_value;
    }

    public function setCmdValue(string $cmd_value): self
    {
        $this->cmd_value = $cmd_value;

        return $this;
    }

    public function getPublished(): bool
    {
        return $this->published;
    }

    public function setPublished(bool $published): self
    {
        $this->published = $published;

        return $this;
    }

    public function getReceived(): bool
    {
        return $this->received;
    }

    public function setReceived(bool $received): self
    {
        $this->received = $received;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    /**
     * @ORM\PreFlush()
     * @throws \Exception
     */
    public function setUpdatedAt(): void
    {
        $this->updatedAt = new \DateTime();
    }

    public function getPlant(): ?Plant
    {
        return $this->plant;
    }

    public function setPlant(?Plant $plant): self
    {
        $this->plant = $plant;

        return $this;
    }

    public function getCanBeDeleted(): bool
    {
        return $this->can_be_deleted;
    }

    public function setCanBeDeleted(bool $can_be_deleted): self
    {
        $this->can_be_deleted = $can_be_deleted;

        return $this;
    }

    public function __toString()
    {
        return $this->getCmdKey() . ':' . $this->getCmdValue();
    }
}

src/Form/NodeCommandType.php
<?php

namespace App\Form;

use App\Entity\NodeCommand;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class NodeCommandType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('cmd_key')
            ->add('cmd_value')
            ->add('published')
            ->add('received')
            ->add('can_be_deleted')
            ->add('plant')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => NodeCommand::class,
        ]);
    }
}

src/Controller/NodeCommandController.php
<?php

namespace App\Controller;

use App\Entity\NodeCommand;
use App\Form\NodeCommandType;
use App\Repository\NodeCommandRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/node/command")
 */
class NodeCommandController extends AbstractController
{
    /**
     * @Route("/", name="node_command_index", methods={"GET"})
     */
    public function index(NodeCommandRepository $nodeCommandRepository): Response
    {
        return $this->render('node_command/index.html.twig', [
            'node_commands' => $nodeCommandRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="node_command_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $nodeCommand = new NodeCommand();
        $form = $this->createForm(NodeCommandType::class, $nodeCommand);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($nodeCommand);
            $entityManager->flush();

            return $this->redirectToRoute('node_command_index');
        }

        return $this->render('node_command/new.html.twig', [
            'node_command' => $nodeCommand,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="node_command_show", methods={"GET"})
     */
    public function show(NodeCommand $nodeCommand): Response
    {
        return $this->render('node_command/show.html.twig', [
            'node_command' => $nodeCommand,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="node_command_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, NodeCommand $nodeCommand): Response
    {
        $form = $this->createForm(NodeCommandType::class, $nodeCommand);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('node_command_index', [
                'id' => $nodeCommand->getId(),
            ]);
        }

        return $this->render('node_command/edit.html.twig', [
            'node_command' => $nodeCommand,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="node_command_delete", methods={"DELETE"})
     */
    public function delete(Request $request, NodeCommand $nodeCommand): Response
    {
        if ($this->isCsrfTokenValid('delete'.$nodeCommand->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($nodeCommand);
            $entityManager->flush();
        }

        return $this->redirectToRoute('node_command_index');
    }
}

templates/node_command/_delete_form.html.twig
<form method="post" action="{{ path('node_command_delete', {'id': node_command.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ node_command.id) }}">
    <button class="btn">Delete</button>
</form>

templates/node_command/_form.html.twig
{{ form_start(form) }}
<table class="table">
    <tr>
        <td>{{ form_label(form.cmd_key, 'cmd_key') }}</td>
        <td>{{ form_widget(form.cmd_key) }}</td>
        <td>{{ form_help(form.cmd_key) }}</td>
        <td style="width: 40%;">{{ form_errors(form.cmd_key) }}</td>
    </tr>
    <tr>
        <td>{{ form_label(form.cmd_value, 'cmd_value') }}</td>
        <td>{{ form_widget(form.cmd_value) }}</td>
        <td>{{ form_help(form.cmd_value) }}</td>
        <td>{{ form_errors(form.cmd_value) }}</td>
    </tr>
    <tr>
        <td>{{ form_label(form.published) }}</td>
        <td>{{ form_widget(form.published) }}</td>
        <td>{{ form_help(form.published) }}</td>
        <td>{{ form_errors(form.published) }}</td>
    </tr>
    <tr>
        <td>{{ form_label(form.received) }}</td>
        <td>{{ form_widget(form.received) }}</td>
        <td>{{ form_help(form.received) }}</td>
        <td>{{ form_errors(form.received) }}</td>
    </tr>
    <tr>
        <td>{{ form_label(form.plant) }}</td>
        <td>{{ form_widget(form.plant) }}</td>
        <td>{{ form_help(form.plant) }}</td>
        <td>{{ form_errors(form.plant) }}</td>
    </tr>
</table>
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}
<style>
    input[type="text"] {
        width: 600px !important;
    }
</style>

templates/node_command/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit NodeCommand{% endblock %}

{% block body %}
    <h1>Edit NodeCommand</h1>

    {{ include('node_command/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('node_command_index') }}">back to list</a>

    {{ include('node_command/_delete_form.html.twig') }}
{% endblock %}

templates/node_command/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}NodeCommand index{% endblock %}

{% block body %}
    <h1>NodeCommand index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Cmd_key</th>
                <th>Cmd_value</th>
                <th>Published</th>
                <th>Received</th>
                <th>CreatedAt</th>
                <th>UpdatedAt</th>
                <th>Can_be_deleted</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for node_command in node_commands %}
            <tr>
                <td>{{ node_command.id }}</td>
                <td>{{ node_command.cmdKey }}</td>
                <td>{{ node_command.cmdValue }}</td>
                <td>{{ node_command.published ? 'Yes' : 'No' }}</td>
                <td>{{ node_command.received ? 'Yes' : 'No' }}</td>
                <td>{{ node_command.createdAt ? node_command.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ node_command.updatedAt ? node_command.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ node_command.canBeDeleted ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('node_command_show', {'id': node_command.id}) }}">show</a>
                    <a href="{{ path('node_command_edit', {'id': node_command.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('node_command_new') }}">Create new</a>
{% endblock %}

templates/node_command/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New NodeCommand{% endblock %}

{% block body %}
    <h1>Create new NodeCommand</h1>

    {{ include('node_command/_form.html.twig') }}

    <a href="{{ path('node_command_index') }}">back to list</a>
{% endblock %}

templates/node_command/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}NodeCommand{% endblock %}

{% block body %}
    <h1>NodeCommand</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ node_command.id }}</td>
            </tr>
            <tr>
                <th>Cmd_key</th>
                <td>{{ node_command.cmdKey }}</td>
            </tr>
            <tr>
                <th>Cmd_value</th>
                <td>{{ node_command.cmdValue }}</td>
            </tr>
            <tr>
                <th>Published</th>
                <td>{{ node_command.published ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Received</th>
                <td>{{ node_command.received ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>CreatedAt</th>
                <td>{{ node_command.createdAt ? node_command.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>UpdatedAt</th>
                <td>{{ node_command.updatedAt ? node_command.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Can_be_deleted</th>
                <td>{{ node_command.canBeDeleted ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('node_command_index') }}">back to list</a>

    <a href="{{ path('node_command_edit', {'id': node_command.id}) }}">edit</a>

    {{ include('node_command/_delete_form.html.twig') }}
{% endblock %}