src/Entity/CustomField.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\Index;
use Doctrine\ORM\Mapping\UniqueConstraint;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CustomFieldRepository")
 * @ORM\Table(name="custom_field", indexes={
 *     @Index(name="index_3_keys", columns={"object_host_id", "object_host_type", "property"}),
 *     @Index(name="index_2_keys", columns={"object_host_id", "object_host_type"}),
 *     @Index(name="index_object_host_id", columns={"object_host_id"}),
 *     }
 *     , uniqueConstraints={@ORM\UniqueConstraint(name="uniq_entry", columns={"object_host_id", "object_host_type", "property"})}
 *     )
 * @ORM\HasLifecycleCallbacks()
 */
class CustomField
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer", options={"unsigned"=true})
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180)
     */
    private $property;

    /**
     * @ORM\Column(type="object")
     */
    private $propertyValue;

    /**
     * @ORM\Column(type="text", length=16777213, options={"default"=""})
     */
    private $propertyValueString;

    /**
     * @ORM\Column(type="bigint", options={"unsigned"=true})
     */
    private $object_host_id;

    /**
     * @ORM\Column(type="string", length=150)
     */
    private $object_host_type;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\Column(type="string", length=150, nullable=true)
     */
    private $propertyValueType;

    public function __construct()
    {
        try {
            $this->setCreatedAt(new \DateTime());
        } catch (\Exception $e) {
        }
        try {
            $this->setUpdatedAt();
        } catch (\Exception $e) {
        }
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getProperty(): string
    {
        if ($this->property === null) {
            return '';
        }
        return $this->property;
    }

    public function setProperty(string $property): self
    {
        $this->property = $property;

        return $this;
    }

    public function getPropertyValue()
    {
        return $this->propertyValue;
    }

    public function setPropertyValue($propertyValue): self
    {
        $this->propertyValue = $propertyValue;
        $this->setPropertyValueString($propertyValue);
        $this->setPropertyValueType(gettype($propertyValue));
        return $this;
    }

    /**
     * @return string
     */
    public function getPropertyValueString(): string
    {
        if ($this->propertyValueString === null) {
            return '';
        }
        return $this->propertyValueString;
    }

    public function setPropertyValueString(string $propertyValueString): self
    {
        $this->propertyValueString = $propertyValueString;

        return $this;
    }

    public function getObjectHostId(): ?int
    {
        return $this->object_host_id;
    }

    public function setObjectHostId(int $object_host_id): self
    {
        $this->object_host_id = $object_host_id;

        return $this;
    }

    /**
     * @return string
     */
    public function getObjectHostType(): string
    {
        if ($this->object_host_type === null) {
            return '';
        }
        return $this->object_host_type;
    }

    public function setObjectHostType(string $object_host_type): self
    {
        $this->object_host_type = $object_host_type;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    /**
     * @param \DateTimeInterface $created_at
     * @return CustomField
     */
    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    /**
     * @ORM\PreUpdate
     * @throws \Exception
     */
    public function setUpdatedAt(): self
    {
        $this->updated_at = new \DateTime();

        return $this;
    }

    /**
     * @return string
     */
    public function getPropertyValueType(): string
    {
        if ($this->propertyValueType === null) {
            return 'None';
        }
        return $this->propertyValueType;
    }

    public function setPropertyValueType(?string $propertyValueType): self
    {
        $this->propertyValueType = $propertyValueType;

        return $this;
    }

    public function __toString()
    {
        return $this->getPropertyValueString();
    }
}

src/Form/CustomFieldType.php
<?php

namespace App\Form;

use App\Entity\CustomField;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CustomFieldType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('property')
            ->add('propertyValue')
            ->add('propertyValueString')
            ->add('object_host_id')
            ->add('object_host_type')
            ->add('created_at')
            ->add('updated_at')
            ->add('propertyValueType')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => CustomField::class,
        ]);
    }
}

src/Controller/CustomFieldController.php
<?php

namespace App\Controller;

use App\Entity\CustomField;
use App\Form\CustomFieldType;
use App\Repository\CustomFieldRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/custom/field")
 */
class CustomFieldController extends AbstractController
{
//    /**
//     * @Route("/", name="custom_field_index", methods={"GET"})
//     */
//    public function index(CustomFieldRepository $customFieldRepository): Response
//    {
//        return $this->render('custom_field/index.html.twig', [
//            'custom_fields' => $customFieldRepository->findAll(),
//        ]);
//    }

//    /**
//     * @Route("/new", name="custom_field_new", methods={"GET","POST"})
//     */
//    public function new(Request $request): Response
//    {
//        $customField = new CustomField();
//        $form = $this->createForm(CustomFieldType::class, $customField);
//        $form->handleRequest($request);
//
//        if ($form->isSubmitted() && $form->isValid()) {
//            $entityManager = $this->getDoctrine()->getManager();
//            $entityManager->persist($customField);
//            $entityManager->flush();
//
//            return $this->redirectToRoute('custom_field_index');
//        }
//
//        return $this->render('custom_field/new.html.twig', [
//            'custom_field' => $customField,
//            'form' => $form->createView(),
//        ]);
//    }

    /**
     * @Route("/{id}", name="custom_field_show", methods={"GET"})
     */
    public function show(CustomField $customField): Response
    {
        return $this->render('custom_field/show.html.twig', [
            'custom_field' => $customField,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="custom_field_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, CustomField $customField): Response
    {
        $form = $this->createForm(CustomFieldType::class, $customField);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();
        }

        return $this->render('custom_field/edit.html.twig', [
            'custom_field' => $customField,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="custom_field_delete", methods={"DELETE"})
     */
    public function delete(Request $request, CustomField $customField): Response
    {
        if ($this->isCsrfTokenValid('delete'.$customField->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($customField);
            $entityManager->flush();
        }

        return $this->redirectToRoute('index');
    }
}

templates/custom_field/_delete_form.html.twig
<form method="post" action="{{ path('custom_field_delete', {'id': custom_field.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ custom_field.id) }}">
    <button class="btn">Delete</button>
</form>

templates/custom_field/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit CustomField{% endblock %}

{% block body %}
    <h1>Edit CustomField</h1>

    {{ include('custom_field/_form.html.twig', {'button_label': 'Update'}) }}

{#    <a href="{{ path('custom_field_index') }}">back to list</a>#}

    {{ include('custom_field/_delete_form.html.twig') }}
{% endblock %}

templates/custom_field/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}CustomField index{% endblock %}

{% block body %}
    <h1>CustomField index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Property</th>
                <th>PropertyValue</th>
                <th>PropertyValueString</th>
                <th>Object_host_id</th>
                <th>Object_host_type</th>
                <th>Created_at</th>
                <th>Updated_at</th>
                <th>PropertyValueType</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for custom_field in custom_fields %}
            <tr>
                <td>{{ custom_field.id }}</td>
                <td>{{ custom_field.property }}</td>
                <td>{{ custom_field.propertyValue }}</td>
                <td>{{ custom_field.propertyValueString }}</td>
                <td>{{ custom_field.objectHostId }}</td>
                <td>{{ custom_field.objectHostType }}</td>
                <td>{{ custom_field.createdAt ? custom_field.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ custom_field.updatedAt ? custom_field.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ custom_field.propertyValueType }}</td>
                <td>
                    <a href="{{ path('custom_field_show', {'id': custom_field.id}) }}">show</a>
                    <a href="{{ path('custom_field_edit', {'id': custom_field.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{#    <a href="{{ path('custom_field_new') }}">Create new</a>#}
{% endblock %}

templates/custom_field/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New CustomField{% endblock %}

{% block body %}
    <h1>Create new CustomField</h1>

    {{ include('custom_field/_form.html.twig') }}

    <a href="{{ path('custom_field_index') }}">back to list</a>
{% endblock %}

templates/custom_field/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}CustomField{% endblock %}

{% block body %}
    <h1>CustomField</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ custom_field.id }}</td>
            </tr>
            <tr>
                <th>Link to Object</th>
                <td>
                    {% if custom_field.objectHostType == 'App\Entity\Plant' %}
                        {{ path('plant_show', {'id': custom_field.objectHostId }) }}
                    {% endif %}
                </td>
            </tr>
            <tr>
                <th>Property</th>
                <td>{{ custom_field.property }}</td>
            </tr>
            <tr>
                <th>PropertyValue</th>
                <td>{{ custom_field.propertyValue }}</td>
            </tr>
            <tr>
                <th>PropertyValueString</th>
                <td>{{ custom_field.propertyValueString }}</td>
            </tr>
            <tr>
                <th>Object_host_id</th>
                <td>{{ custom_field.objectHostId }}</td>
            </tr>
            <tr>
                <th>Object_host_type</th>
                <td>{{ custom_field.objectHostType }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ custom_field.createdAt ? custom_field.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Updated_at</th>
                <td>{{ custom_field.updatedAt ? custom_field.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>PropertyValueType</th>
                <td>{{ custom_field.propertyValueType }}</td>
            </tr>
        </tbody>
    </table>

{#    <a href="{{ path('custom_field_index') }}">back to list</a>#}

    <a href="{{ path('custom_field_edit', {'id': custom_field.id}) }}">edit</a>

    {{ include('custom_field/_delete_form.html.twig') }}
{% endblock %}